Homework 07
Otus-DevOps-2017-11/mrgreyves_infra pull request #5
Opened 2017-12-21 17:46 UTC by mrgreyves

2017-12-22 15:45 UTC, vitkhab requested changes
На самом деле все очень классно. Проблем разобраться с проектом у меня не возникло.

Есть два требования на доработку, скорее даже на причесывание:
- поменять `"null"` на `null` в переменных в ubuntu16.json
- привети `image_name` в immutable.json в соответствие с `image_family`

И ответить на вопрос: Почему ты используешь пользователя `root` при создании образов?

Из плюсов заметил:
- Прекрасная документация. Прям огонь!
- Успешно выполнил обе задания со звездочками.
- Для immutable образа использовал base образ как базовый
- Технически все сделано опрятно
- Вижу, что изучал возможности googlecompute builder'а

2017-12-22 15:45 UTC, vitkhab commented on packer/immutable.json
> +         "ssh_username":"root",
Почему ты используешь пользователя `root`, хотя в методичке мы используем пользователя `appuser`?
Разделять права по пользователям - хорошая практика, даже если больше ничего на сервере не запущено.

2017-12-22 15:45 UTC, vitkhab commented on packer/variables.json.example
> +   "source_image_family":"Source OS",
Я предпочитаю в переменных по умолчанию указывать наиболее возможный вариант. Тут главное осознано подходить к тому, почему ты написал несуществующее семейство образов.

Раз у нас две конфигурации, то можно было бы создать и второй пример с переменными.
Для base образа указать `ubuntu-1604-lts`
Для full образа указать `reddit-base`

2017-12-22 15:45 UTC, vitkhab commented on packer/ubuntu16.json
> +         "source_image_family":"null",
Запись должна быть без кавычек.
То есть `null` вместо `"null"`

2017-12-22 20:33 UTC, Nklya commented
Описание PR нужно заполнять. Хотя бы в базовом варианте. Например

2017-12-24 10:06 UTC, mrgreyves commented
Сделал все правки на которые указал Виталий. Использование пользователя root, это моя болезненная привычка от которой надо избавляться. К тому же в проектах которые смотрят в интернет:))  Поправил лишние кавычки в ubuntu16.json. Так же поправил файл variables. Указал близкие к истине параметры. (Кавычки проморгал, так как решил в последний момент использовать файл с переменными). Так же заполнил описание PR как указал Николай.

2017-12-25 09:37 UTC, vitkhab requested changes
Убери, пожалуйста, лишнюю запятую в `variables.json`. 

Правка `source_image_family` в `immutable.json` на свое усмотрение

2017-12-25 09:37 UTC, vitkhab commented on packer/variables.json.example
> +   "source_image_family":"ubuntu-1604-lts",
Лишняя запятая

2017-12-25 09:37 UTC, vitkhab commented on packer/immutable.json
> +         "source_image_family":"{{user `source_image_family`}}",
Здесь явно требуется образ из семейства `reddit-base`. Что ограничивает использование одного `variables.json` файла для `base` и `full` образов одновременно

2017-12-25 10:05 UTC, mrgreyves commented
Поправил лишнюю запятую в файле с переменными. Изменил source_image_family в immutable.json, указал reddit-base

2017-12-25 11:49 UTC, vitkhab approved these changes
Молодец!

2017-12-25 11:50 UTC, merged