Выполнение ДЗ 8
Otus-DevOps-2017-11/mrgreyves_infra pull request #6
Opened 2017-12-26 19:13 UTC by mrgreyves

2017-12-27 09:10 UTC, Nklya requested changes
Заполни пожалуйста описание PR

2017-12-28 09:31 UTC, Nklya approved these changes
Добрый день.

Владимир, все сделано отлично. Хорошее описание в ридми.

Да, подход с count лучше чем копипаст кода. Добавил это в ДЗ.

Единственное замечание по поводу первого задания со *.

2017-12-28 09:31 UTC, Nklya commented on README.md
> +Для добавления нескольких ключей можно использовать конструкцию
В этом задании нужно было рассмотреть менеджмент ключей на уровне метаданных всего проекта.
А ты видимо рассмотрел менеджмент ключей создаваемого инстанса.

2017-12-28 09:34 UTC, mrgreyves commented on README.md
> +Для добавления нескольких ключей можно использовать конструкцию
Я тебя понял. Спасибо за комментарий:)

2017-12-28 09:35 UTC, merged